
source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '15.0' 

def common
    
    pod 'HorizonCalendar', '1.16.0'
    pod 'Alamofire', '~> 5.10.1'
    pod 'CCGestureLock'
    pod 'GoogleTagManager', '~> 7.4.2'
    pod 'Firebase/Analytics', '10.24.0'
    pod 'Firebase/Crashlytics', '10.24.0'
    pod 'Firebase/Performance', '10.24.0'
    pod 'SideMenu', '~> 6.0'

    pod 'JCore', '5.2.2'
    pod 'JPush', '5.9.0'

    pod 'SDWebImageWebPCoder'
    pod 'MarqueeLabel'
end

target 'WorkPal' do
  use_frameworks!
  common

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = "NO"
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14'
      if ['iProov', 'Socket.IO-Client-Swift', 'Starscream'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            end
      end
    end
  end
end
